#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math
import hashlib, heapq

class Receiver:
    def __init__(self):
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.port = self.socket.getsockname()[1]
        self.log("Bound to port %d" % self.port)

        self.remote_host = None
        self.remote_port = None

        self.packet_pq = []    # use a heap to store out-of-order packets
        self.next_seq = 0      # the expected sequence number to be received
        self.received = set()  # keep track of received sequence numbers to detect duplicates

    def send(self, message):
        # self.log("Sent message %s" % json.dumps(message))
        self.socket.sendto(json.dumps(message).encode("utf-8"), (self.remote_host, self.remote_port))

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        # Grab the remote host/port if we don't already have it
        if self.remote_host is None:
            self.remote_host = addr[0]
            self.remote_port = addr[1]

        # Make sure we're talking to the same remote host
        if addr != (self.remote_host, self.remote_port):
            self.log("Error: Received response from unexpected remote; ignoring")
            return None
        else:
            # self.log("Received message %s" % data.decode("utf-8"))
            return json.loads(data.decode("utf-8"))

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    @staticmethod
    def checksum(data):
        return hashlib.md5(data.encode()).hexdigest()

    def verify_checksum(self, msg):
        """
        Verify the checksum field of the received message.
        :param msg: the received message.
        :return: True if checksum matches the data, False otherwise.
        """
        sent = msg.get("checksum", "")
        received = self.checksum(msg.get("data", ""))
        return sent == received

    def send_ack(self, sequence):
        """
        Send an acknowledgement message back to the sender.
        :param sequence: the sequence number to be acknowledged.
        """
        ack = {"type": "ack", "seq": sequence}
        hashcode = self.checksum(json.dumps(ack))
        ack["checksum"] = hashcode
        self.send(ack)

    def handle_receive(self, msg):
        # ignore duplicated packets
        seq = msg["seq"]
        if seq in self.received:
            return
        self.received.add(seq)

        # packet is received in-order, print out data to stdout
        if seq == self.next_seq:
            print(msg["data"], end='', flush=True)
            self.next_seq += 1
        # received out-of-order, add to the priority queue for future process
        else:
            heapq.heappush(self.packet_pq, (seq, msg))

    def process_heap(self):
        while self.packet_pq and self.next_seq == self.packet_pq[0][0]:
            _, packet = heapq.heappop(self.packet_pq)
            print(packet["data"], end='', flush=True)
            self.next_seq += 1

    def run(self):
        while True:
            socks = select.select([self.socket], [], [])[0]
            for conn in socks:
                msg = self.recv(conn)
                if msg and msg["type"] == "msg":
                    # verify checksum for error detection
                    if not self.verify_checksum(msg):
                        self.log(f"Corrupt packet {msg.get('seq', '')}")
                        continue

                    # send back an ACK if the packet is correct
                    self.send_ack(msg["seq"])

                    self.handle_receive(msg)
                    self.process_heap()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='receive data')
    args = parser.parse_args()
    receiver = Receiver()
    receiver.run()
